### ISSUE TITLE
how to install it

### ISSUE THREAD

**Issue by Aneeqasif** [LiHRaM/zathura-markdown-rs#1]

**Comment by LiHRaM** [comment]
Hi @Aneeqasif, it should be as simple as building it in release mode and moving it to the directory where Zathura looks for plugins. Specifically, if you are on a standard unix system where Zathura's plugins directory is set as `/usr/lib/zathura`, then you would run:

```bash
cargo build --release
sudo install -D ./target/release/*.so /usr/lib/zathura/
```

Zathura should automatically use the plugin the next time it starts.

EDIT: There's not much it can do though.

**Comment by LiHRaM** [comment]
I'm closing this for now, as I've answered the question, but feel free to reopen if anything is unclear. :)

**Comment by panv-00** [comment]
I think it would be good to add below to the main README:

to install:
`make`
`cargo build --release`
`sudo install -D ./target/release/*.so /usr/lib/zathura/`
